API Documentation Improvements
imagerelay/API pull request #34
Opened 2021-06-16 17:36 UTC by ofelcan164

All pages have been updated to be more cohesive and simple to understand.

2021-06-16 19:17 UTC, mdoyle13 commented on sections/file_types.md
> +* `GET /file_types.json` will return all the file types for the authenticated user.
I don't think this is actually true. I believe its for the client

2021-06-16 19:18 UTC, mdoyle13 commented on sections/file_types.md
> +* `GET /file_types.json` will return all the file types for the authenticated user.
line 8 of asset types controller is `current_user.client.metagroups.with_sorted_metaterms_and_options.order(:name))`

2021-06-16 19:24 UTC, mdoyle13 commented on sections/keywording.md
> +* `GET /keyword_sets.json` will return `200 OK` and the authenticated user's list of keyword sets.
I believe this returns the client's keyword sets if the user has permission for metadata

2021-06-16 19:34 UTC, justinperkins requested changes

2021-06-16 19:34 UTC, justinperkins commented on sections/uploads.md
> +The upload API is how you can add files to Image Relay. Files are uploaded to Image Relay through the creation of upload jobs, and then individual files are sent up in chunks.
@ofelcan164 can you add a sentence here that describes nested files along with a link to the new Nested Files page?

2021-06-16 23:58 UTC, ofelcan164 commented on sections/file_types.md
> +* `GET /file_types.json` will return all the file types for the authenticated user.
@mdoyle13 I pushed the change. Let me know if that is what you were thinking.

2021-06-16 23:58 UTC, ofelcan164 commented on sections/keywording.md
> +* `GET /keyword_sets.json` will return `200 OK` and the authenticated user's list of keyword sets.
@mdoyle13 Done.

2021-06-16 23:59 UTC, ofelcan164 commented on sections/uploads.md
> +The upload API is how you can add files to Image Relay. Files are uploaded to Image Relay through the creation of upload jobs, and then individual files are sent up in chunks.
@justinperkins Added a a bit there. Let me know if that looks good.

2021-06-17 13:42 UTC, mdoyle13 requested changes

2021-06-17 13:42 UTC, mdoyle13 commented on sections/file_types.md
> +* `GET /file_types.json` will return all the file types for the authenticated user.
@ofelcan164 I think you forgot to push the changes. I'm not seeing them.

2021-06-17 14:51 UTC, ofelcan164 commented on sections/file_types.md
> +* `GET /file_types.json` will return all the file types for the authenticated user.
Fairly confident I did, and when I push again it says everything is up to do. So I am confused.
This is the link to the commit I made yesterday @mdoyle13 https://github.com/imagerelay/API/pull/34/commits/12d639d2497f877c025c209c33a82f1de7d75178.

2021-06-17 15:05 UTC, mdoyle13 commented on sections/file_types.md
> +* `GET /file_types.json` will return all the file types for the authenticated user.
That's odd. I see the changes now. Github may be having caching issues.

2021-06-17 15:05 UTC, mdoyle13 approved these changes
I'm good with this. Let's wait for @justinperkins approval before merging into master

2021-06-17 22:48 UTC, justinperkins approved these changes

2021-06-17 22:48 UTC, merged